// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYsb1cuIVMKTXcrvEMGjn782cIDspKEUM',
    appId: '1:167434907053:web:5e36195491e5ca7f9b4524',
    messagingSenderId: '167434907053',
    projectId: 'chit-chat-8b094',
    authDomain: 'chit-chat-8b094.firebaseapp.com',
    storageBucket: 'chit-chat-8b094.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUko1mxry8Kynlm0kRdmrFY_e4dO_VS_8',
    appId: '1:167434907053:android:813dd3b0af9011419b4524',
    messagingSenderId: '167434907053',
    projectId: 'chit-chat-8b094',
    storageBucket: 'chit-chat-8b094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb_6lh7MMQbMXPivO5saI-EIXpGCR2Vbg',
    appId: '1:167434907053:ios:7167aaed32db8fc39b4524',
    messagingSenderId: '167434907053',
    projectId: 'chit-chat-8b094',
    storageBucket: 'chit-chat-8b094.firebasestorage.app',
    iosBundleId: 'com.example.firebasechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb_6lh7MMQbMXPivO5saI-EIXpGCR2Vbg',
    appId: '1:167434907053:ios:7167aaed32db8fc39b4524',
    messagingSenderId: '167434907053',
    projectId: 'chit-chat-8b094',
    storageBucket: 'chit-chat-8b094.firebasestorage.app',
    iosBundleId: 'com.example.firebasechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYsb1cuIVMKTXcrvEMGjn782cIDspKEUM',
    appId: '1:167434907053:web:a21402fd2f9416509b4524',
    messagingSenderId: '167434907053',
    projectId: 'chit-chat-8b094',
    authDomain: 'chit-chat-8b094.firebaseapp.com',
    storageBucket: 'chit-chat-8b094.firebasestorage.app',
  );

}